#requires -version 5
<#
    Auto-accumulate research data every trading day via two Windows Scheduled Tasks (weekdays only).

    08:55  Accumulate : refresh raw daily bars + rebuild the point-in-time universe for any new trading day.
    09:14  Recorder   : start the 1-minute bid/ask recorder; it flushes and exits by itself after 15:00 close.
                        (09:14 instead of 09:25 so we also capture the opening call-auction book.)

    Why a .cmd wrapper: Register-ScheduledTask -Argument quoting is fragile inside cmd, so we generate a
    tiny .cmd that pins the repo path, the absolute bun path and log redirection. The task just calls it.

    Run (normal PowerShell, no admin; tasks run as the current interactive user):
        powershell -ExecutionPolicy Bypass -File scripts\setup-research-tasks.ps1
    Idempotent: re-run anytime, -Force overwrites same-name tasks. Edit the two lines at the bottom to retime.
    Uninstall: scripts\remove-research-tasks.ps1

    NOTE: keep this file ASCII-only. Windows PowerShell 5.1 decodes non-BOM scripts as the system ANSI
    codepage (GBK here), and multibyte UTF-8 in comments/strings can break the parser.
#>
$ErrorActionPreference = "Stop"

$scriptsDir = $PSScriptRoot
$repo = (Resolve-Path (Join-Path $scriptsDir "..")).Path

# Scheduler context may not have bun on PATH; resolve an absolute path now and bake it into the .cmd.
$bunCmd = Get-Command bun -ErrorAction SilentlyContinue
if (-not $bunCmd) {
    throw "bun not found on PATH. Install bun or set the `$bun variable below to an absolute path."
}
# Get-Command may resolve to a bun.ps1 shim (npm/hermes style). cmd.exe cannot run a .ps1 from
# a batch wrapper: it goes through the .ps1 file association, the task reports exit 0, and nothing
# ever runs. The generated .cmd must therefore point at a real .exe binary.
$bun = $bunCmd.Source
if ($bun -notmatch '\.exe$') {
    $shimDir = Split-Path $bun
    $candidates = @((Join-Path $shimDir 'bun.exe'), (Join-Path $shimDir 'node_modules\bun\bin\bun.exe'))
    foreach ($cand in $candidates) {
        if (Test-Path $cand) { $bun = $cand; break }
    }
    if ($bun -notmatch '\.exe$') { throw "bun resolved to a non-exe shim ($bun) and no bun.exe sits next to it. Set `$bun to an absolute bun.exe path." }
}

$logDir = Join-Path $repo "data\research"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

function Write-CmdWrapper {
    param([string]$Name, [string]$TsScript, [string]$LogName)
    $path = Join-Path $scriptsDir $Name
    $lines = @(
        '@echo off',
        'rem Auto-generated by setup-research-tasks.ps1 (contains machine-specific absolute paths). Do not edit.',
        'cd /d "%~dp0.."',
        "`"$bun`" $TsScript 1>> `"$LogName`" 2>&1"
    )
    Set-Content -Path $path -Value $lines -Encoding ASCII
    return $path
}

function Register-WeekdayTask {
    param([string]$TaskName, [string]$Command, [string]$AtTime, [int]$LimitHours)
    $action    = New-ScheduledTaskAction -Execute $Command -WorkingDirectory $repo
    $trigger   = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Monday,Tuesday,Wednesday,Thursday,Friday -At $AtTime
    $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive
    $settings  = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
                    -ExecutionTimeLimit (New-TimeSpan -Hours $LimitHours) -MultipleInstances IgnoreNew
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null
    Write-Host ("Registered: {0}  @ {1} (Mon-Fri)" -f $TaskName, $AtTime)
}

$accCmd = Write-CmdWrapper -Name ".run-accumulate.cmd" -TsScript "scripts\research-accumulate.ts" -LogName (Join-Path $logDir ".cron-accumulate.log")
$recCmd = Write-CmdWrapper -Name ".run-recorder.cmd"    -TsScript "scripts\record-research-minutes.ts" -LogName (Join-Path $logDir ".cron-recorder.log")

Register-WeekdayTask -TaskName "AShareTrader Research Accumulate" -Command $accCmd -AtTime "08:55" -LimitHours 2
Register-WeekdayTask -TaskName "AShareTrader Research Recorder"   -Command $recCmd -AtTime "09:14" -LimitHours 8

Write-Host ""
Write-Host "Done. Every weekday it will automatically:"
Write-Host "  08:55  refresh raw daily bars + backfill new-day PIT universe"
Write-Host "  09:14  record 1-minute book (self-exits after 15:00 close)"
Write-Host ("Logs: {0}\.cron-accumulate.log / .cron-recorder.log" -f $logDir)
Write-Host "Tasks run only while you are logged in; holidays/no-data days the scripts no-op and exit on their own."
Write-Host "Uninstall: powershell -ExecutionPolicy Bypass -File scripts\remove-research-tasks.ps1"
