#requires -version 5
<#
    Auto-start the paper-trading ENGINE on weekdays so Jev decision + auto buy/sell
    runs unattended during the trading session (open decision window 09:45-14:57).

    Weekday 09:00 : start `bun run src/index.ts` (MODEL/key come from .env).
                    It holds the single-writer ledger lock; the daily data tasks
                    (research-accumulate / recorder) are separate and do not need it.
    ExecutionTimeLimit auto-kills it after the session so it doesn't linger and
    never collides with the next day's start. MultipleInstances=IgnoreNew prevents
    double starts (the lock would reject a second writer anyway).

    Requires the manual dev instance to be stopped first (it holds port 3005 + the lock).

    Run (normal PowerShell, no admin; runs as current interactive user):
        powershell -ExecutionPolicy Bypass -File scripts\setup-engine-task.ps1
    Uninstall: scripts\remove-engine-task.ps1
    Keep ASCII-only: Windows PowerShell 5.1 decodes non-BOM scripts as ANSI (GBK here).
#>
$ErrorActionPreference = "Stop"

$scriptsDir = $PSScriptRoot
$repo = (Resolve-Path (Join-Path $scriptsDir "..")).Path

$bunCmd = Get-Command bun -ErrorAction SilentlyContinue
if (-not $bunCmd) { throw "bun not found on PATH. Install bun or set `$bun to an absolute path." }

# Get-Command may resolve to a bun.ps1 shim (npm/hermes style). cmd.exe cannot run a .ps1 from
# a batch wrapper: it goes through the .ps1 file association, the task reports exit 0, and
# nothing ever runs. The generated .cmd must therefore point at a real .exe binary.
$bun = $bunCmd.Source
if ($bun -notmatch '\.exe$') {
    $shimDir = Split-Path $bun
    $candidates = @((Join-Path $shimDir 'bun.exe'), (Join-Path $shimDir 'node_modules\bun\bin\bun.exe'))
    foreach ($cand in $candidates) {
        if (Test-Path $cand) { $bun = $cand; break }
    }
    if ($bun -notmatch '\.exe$') { throw "bun resolved to a non-exe shim ($bun) and no bun.exe sits next to it. Set `$bun to an absolute bun.exe path." }
}

# Keep the generated .cmd pure ASCII by referring to the user profile symbolically.
# Regression (fixed 2026-09-28): the wrapper baked in an absolute "C:\Users\<name>\..." path and was
# written with -Encoding ASCII, so a non-ASCII user name became "??" and every task launch died with
# "the system cannot find the path specified". The 09:00 engine auto-start had never actually worked;
# the process only kept running because a session had started it by hand.
$bunRef = $bun
if ($bunRef.StartsWith($env:USERPROFILE, [System.StringComparison]::OrdinalIgnoreCase)) {
    $bunRef = '%USERPROFILE%' + $bunRef.Substring($env:USERPROFILE.Length)
}

$logDir = Join-Path $repo "data"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

# Generate a machine-specific cmd wrapper (absolute bun path baked in; gitignored).
$cmdPath = Join-Path $scriptsDir ".run-engine.cmd"
$lines = @(
    '@echo off',
    'rem Auto-generated by setup-engine-task.ps1 (contains machine-specific absolute paths). Do not edit.',
    'cd /d "%~dp0.."',
    "`"$bunRef`" run src\index.ts 1>> `"$logDir\.engine.cron.log`" 2>&1"
)
# Default (system ANSI) rather than ASCII: ASCII would destroy any residual non-ASCII byte.
Set-Content -Path $cmdPath -Value $lines -Encoding Default

$action    = New-ScheduledTaskAction -Execute $cmdPath -WorkingDirectory $repo
$trigger   = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Monday,Tuesday,Wednesday,Thursday,Friday -At "09:00"
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive
$settings  = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
                -ExecutionTimeLimit (New-TimeSpan -Hours 7) -MultipleInstances IgnoreNew

Register-ScheduledTask -TaskName "AShareTrader Engine (Paper)" -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null

Write-Host "Registered: AShareTrader Engine (Paper)  @ 09:00 (Mon-Fri), auto-stops after ~7h."
Write-Host ("Wrapper: {0}" -f $cmdPath)
Write-Host ("Log:     {0}\.engine.cron.log" -f $logDir)
Write-Host "It runs only while you are logged in. To trigger now for a smoke test:"
Write-Host '  Start-ScheduledTask -TaskName "AShareTrader Engine (Paper)"'
